# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-15 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0055_auto_20220913_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'40b4710a-16b7-4180-ac82-d14d5f045357', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 11, 41, 16, 678000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'a46fe549-1003-4ecc-8000-c39e3808a90a', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'9636c58a-e493-4e5b-a6d7-0f0bbfb3baca', max_length=1024),
        ),
    ]
