# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-15 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0057_auto_20220915_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'5d4f37d4-04a7-4271-8879-44ffed0d8c7f', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 23, 18, 9, 691000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'c30cea45-4a09-469e-89be-586c424f3f98', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'3ac67301-c49b-4136-b266-ed08e57823a0', max_length=1024),
        ),
    ]
