# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-15 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0058_auto_20220915_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'5d5b8d17-110c-42da-8cf8-ad7f5417031c', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 23, 33, 23, 253000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'a2b95f91-4f65-4a7b-8c35-7cc1b8b8c2b5', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'ab8f192b-6d4a-4e94-bf01-fc5283f076cb', max_length=1024),
        ),
    ]
