# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0060_auto_20220916_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'30fc81e2-b48b-4536-a0e6-688669acf139', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 10, 37, 37, 714000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'c372c44d-47e4-44aa-aeb8-7fe36e26f64f', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'eb78462c-a623-4426-91aa-abd55c8c053f', max_length=1024),
        ),
    ]
