# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0061_auto_20220916_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'e26df9a2-360c-44e1-8be0-7f520cc94255', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 12, 29, 50, 891000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'85b75057-be75-4491-b62a-c7e5e76656dc', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'1fe2df67-db5c-41b7-9f38-11326a7a94cc', max_length=1024),
        ),
    ]
