# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0062_auto_20220916_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'9851d9c7-a899-48a6-af9a-8c9f00191cfc', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 12, 42, 14, 219000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'970c0be1-f13d-49be-8a45-fd17c3b159dc', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'993df58b-bcb7-4847-9fd4-82dac25d76e1', max_length=1024),
        ),
    ]
