# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0063_auto_20220916_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'f7492324-1246-49d5-9854-edb832ec2812', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 14, 25, 4, 486000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'2b297adf-e1ed-412b-96e1-7fb7e1438b87', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'051698c3-f2e5-43d1-a22e-cdf8469bb699', max_length=1024),
        ),
    ]
