# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-16 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0064_auto_20220916_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'c5acb131-a14e-412e-8af9-408c116ec025', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 16, 11, 47, 341000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'58bf9bd7-096c-4605-9ac4-b881ea459f64', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'50171e05-3042-4ad7-b41d-3644afeca776', max_length=1024),
        ),
    ]
