# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-19 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0066_auto_20220916_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'c867a328-15b9-425b-8c07-42b8de1c026d', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 12, 13, 24, 396000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'c2d997f5-be65-46a7-9fa0-dc6d88640e3a', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'f0619b3e-9e7b-4b39-bfab-16c0e7e6ab7a', max_length=1024),
        ),
    ]
