# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-19 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0068_auto_20220919_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'e62728d9-80ac-4ee6-b0a0-221e865d4463', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 14, 31, 48, 121000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'a174a3bd-de29-4b3e-bd8c-9aea99b9206b', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'ba31e6fb-dd5d-4312-ba30-0cf4dddb9a1b', max_length=1024),
        ),
    ]
