# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-20 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0069_auto_20220919_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'22f4af2c-0a26-4748-a0d1-c0a85da7df92', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 12, 16, 48, 875000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'9930a828-1fd3-4d07-9066-e2688b6534d4', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'7ad29e37-7c49-440b-a0ef-64df839cda09', max_length=1024),
        ),
    ]
