# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-20 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggies_models', '0070_auto_20220920_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(default=b'595bdd84-a80d-4018-9d3b-78c1ec5040a3', max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 12, 41, 512000)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='uuId',
            field=models.CharField(default=b'a554c3b6-c6f4-4d3d-a7cc-fe20555d8393', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=b'e3e63c43-bc68-4b21-b2d2-99f782a11082', max_length=1024),
        ),
    ]
